### ISSUE TITLE
Error queue name cannot be specified

### ISSUE THREAD

**Issue by SeanFeldman** [ParticularLabs/NServiceBus.Serverless#8]
Conventional NServiceBus endpoints can specify error queue name.
With Serverless package it's not currently possible due to the overload that takes only `bool` flag.

https://github.com/ParticularLabs/NServiceBus.Serverless/blob/4990bd19bcaefb790e66167919a5be78eff0e9ed/src/NServiceBus.Serverless/ServerlessEndpointConfiguration.cs#L70

This will force to always use error queue named `error` w/o an option to override the name. The package should allow specifying customer-specific error queue name.

**Comment by timbussmann** [comment]
this can still be configured using the `AdvancedConfiguration` configuration, but +1 to make add an overload which accepts an error queue name as an optional parameter to let users specify the error queue via the "main API"

**Comment by SeanFeldman** [comment]
Discussed and we'll implement as part of the work to build an experimental package for NServiceBus with Azure Functions.
